customer/urls.py
from django.urls import path
from .views import *

app_name = "customer"
urlpatterns = [
    path('', home, name="home"),
    path('login', login, name="login"),
    path('register', register, name="register"),
    path('cmp_register', complete_register, name="complete_register"),
    path('logout', logout, name="logout"),
    path('profile', profile, name="profile"),
    path('myorders', my_orders, name="my_orders"),
    path('shops/<int:shop_id>/result', shop_page_result, name="shop_page_result"),
    path('shops/<int:shop_id>/<int:product_id>',
         product_page, name="product_page"),
    path('shops/<int:shop_id>/order', place_order, name='place_order'),
    path('shops/<int:shop_id>', shop_page, name="shop_page"),
    path('results/search', results, name="results"),
]

shopify/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("customer.urls", namespace="customer")),
    path('partner_with_us/', include("shopowner.urls", namespace="shopowner")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.db import models
from django.contrib.auth.hashers import make_password, check_password

# Create your models here.


class Customer(models.Model):

    GENDER = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other')
    )
    name = models.CharField(verbose_name="Name", max_length=100, null=True)
    email = models.EmailField(verbose_name="Email", max_length=100)
    password = models.CharField(verbose_name="Password", max_length=100)
    age = models.IntegerField(verbose_name="Age", null=True)
    contact_number = models.CharField(
        verbose_name="Contact Number", max_length=13, null=True)
    address = models.CharField(
        verbose_name="Address", max_length=200, null=True)
    city = models.CharField(verbose_name="City", max_length=50, null=True)
    state = models.CharField(verbose_name="State", max_length=50, null=True)
    gender = models.CharField(verbose_name="Gender",
                              max_length=1, choices=GENDER, null=True)
    image = models.ImageField(
        upload_to="customer/images", default="customer/images/custdefault.jpg")
    complete_info = models.BooleanField(
        verbose_name="Complete Registraiton", default=False)

    def __str__(self):
        return self.name

    def save(self, change_password=False, *args, **kwargs):
        if self.complete_info == False or change_password:
            hashed_password = make_password(self.password)
            self.password = hashed_password
        super(Customer, self).save(*args, **kwargs)

    def check_Customer_password(self, password):
        if check_password(password, self.password):
            return True
        return False

customer/views.py
from django.http.response import HttpResponse, HttpResponseRedirect

from django.shortcuts import render, redirect

from django.core import serializers

from customer.models import Customer

from django.contrib.auth.hashers import make_password, check_password

from shopowner.models import Order, Product, Shopowner, Shop, Notification


# Create your views here.


def home(request):

    # if request.method == "POST":

    #     scity = request.POST['scity']

    #     scity = scity.lower()

    #     if request.POST.get('shop'):

    #         print('shop name is ', request.POST['shop'])

    #     elif request.POST.get('product'):

    #         print('product name is ', request.POST['product'])

    #     sshop = request.POST['shop']

    #     sshop = sshop.lower()

    #     if len(sshop) == 0:

    #         return redirect('customer:results', scity)

    #     return redirect('customer:results', scity, sshop)

    #     return HttpResponse("HI There")

    if request.session.has_key("customer_email"):

        cust_email = request.session['customer_email']

        cust = Customer.objects.get(email=cust_email)

        return render(request, 'customer/home.html', {

            "cust": cust

        })

    return render(request, "customer/home.html")


def login(request):

    if request.method == "POST":

        email = request.POST['email']

        password = request.POST['password']

        # if customer with this email doesnot exists

        if Customer.objects.filter(email=email).exists():

            cust = Customer.objects.get(email=email)

            # if customer password doesnot matchs

            if cust.check_Customer_password(password) == False:

                error = "password is incorrect"

                return render(request, "customer/login.html", {

                    'error': error

                })

            # success then redirect to home

            # as successful therefore we create session

            request.session['customer_email'] = email

            return HttpResponseRedirect("/")

        else:

            error = "Customer with this email does not exist, You can register yourself first"

            return render(request, "customer/login.html", {

                "error": error,

            })

    return render(request, "customer/login.html")


def register(request):

    if request.method == "POST":

        email = request.POST['email']

        name = request.POST['name']

        password = request.POST['password']

        cpassword = request.POST['cpassword']

        # check if customer already exists

        if Customer.objects.filter(email=email).exists():

            error = "Customer with this email already exist"

            return render(request, "customer/register.html", {

                "error": error

            })

        # password check

        if password != cpassword:

            error = "Password dosent match"

            return render(request, "customer/register.html", {

                'error': error

            })

        obj = Customer(email=email, password=password, name=name)

        obj.save()

        request.session['customer_email'] = email

        return redirect('customer:complete_register')

    return render(request, "customer/register.html")


def complete_register(request):

    email = request.session['customer_email']

    cust = Customer.objects.get(email=email)

    if request.method == "POST":

        # now putting all data in customer object

        cust.name = request.POST['name']

        cust.age = request.POST['age']

        cust.contact_number = request.POST['contact_number']

        cust.address = request.POST['address']

        cust.city = request.POST['city']

        cust.state = request.POST['state']

        cust.gender = request.POST['gender']

        cust.complete_info = True

        try:

            cust.image = request.FILES['image']

        except:
            pass

        cust.save()

        return redirect('/')

    return render(request, 'customer/cmp_registerForm.html', {

        'cust': cust,

        'none': None

    })


def logout(request):

    if request.session.has_key('customer_email'):

        if request.method == "POST":

            del request.session['customer_email']

            return render(request, 'customer/logout.html', {

                'logout': True

            })

        cust_email = request.session['customer_email']

        customer = Customer.objects.get(email=cust_email)

        return render(request, 'customer/logout.html', {

            'cust': customer

        })

    return redirect('customer:home')


def profile(request):

    if not request.session.has_key("customer_email"):

        return redirect('customer:home')

    cust_email = request.session['customer_email']

    customer = Customer.objects.get(email=cust_email)

    return render(request, "customer/profile.html", {

        'cust': customer

    })


def results(request):

    try:

        cust_email = request.session['customer_email']

        customer = Customer.objects.get(email=cust_email)

    except:

        customer = None

    city_name = request.GET['city_name']

    if request.GET.get('shop'):

        # it will return shop list

        shop_name = request.GET['shop']

        shops_list = Shop.objects.filter(

            city=city_name, name__icontains=shop_name)

        # print("Shop list, ", shops_list)

        list_length = len(shops_list)

        return render(request, "customer/results.html", {

            'shops': shops_list,

            'cust': customer,

            'list_length': list_length

        })

    if request.GET.get('product'):

        # it will return product list avilable

        product_name = request.GET['product']

        product_list = Product.objects.filter(

            name__icontains=product_name, shop__city=city_name)

        list_length = len(product_list)

        # print("Product Name ", product_list)

        return render(request, "customer/results.html", {

            'products': product_list,

            'cust': customer,

            'list_length': list_length

        })

    shops = Shop.objects.filter(city=city_name)

    list_length = len(shops)

    return render(request, "customer/results.html", {

        'shops': shops,

        'cust': customer,

        'list_length': list_length

    })


def shop_page(request, shop_id):

    try:

        shop = Shop.objects.get(id=shop_id)

    except:

        shop = None

    try:

        cust_email = request.session['customer_email']

        customer = Customer.objects.get(email=cust_email)

    except:

        customer = None

    if not shop:

        return render(request, "customer/shop_profile.html", {

            'not_found': True

        })

    product_request_done = None

    if request.method == "POST" and request.POST.get("product_request") == "submit":

        product_name = request.POST['product_name']

        # for making product request user have to login first

        if not request.session.has_key('customer_email'):

            return redirect("customer:login")

        # if logined then we will make request

        cust_email = request.session['customer_email']

        customer = Customer.objects.get(email=cust_email)

        req = "i need " + product_name

        notification = Notification(

            customer=customer, message=req, tag="request", shop=shop)

        notification.save()

        product_request_done = True

    context = {

        'shop': shop,

        'products': shop.products.all()[:4],

        'cust': customer,

        'product_request_done': product_request_done


    }

    return render(request, "customer/shop_profile.html", context=context)


def shop_page_result(request, shop_id):

    product_name = request.GET['product_name']

    try:

        cust_email = request.session['customer_email']

        customer = Customer.objects.get(email=cust_email)

    except:

        customer = None

    shop = Shop.objects.get(id=shop_id)

    products = Product.objects.filter(name__icontains=product_name, shop=shop)

    list_length = len(products)

    return render(request, "customer/product_result.html", {

        'products': products,

        'list_length': list_length,

        'shop': shop,

        'cust': customer,

        'pname': product_name,

    })


def my_orders(request):

    if not request.session.has_key('customer_email'):

        return redirect('customer:login')

    customer_email = request.session['customer_email']

    customer = Customer.objects.get(email=customer_email)

    order_list = Order.objects.filter(customer=customer)

    return render(request, 'customer/my_orders.html', {

        'cust': customer,

        'order_list': order_list,

    })


def place_order(request, shop_id):

    # print("path is", request.path)

    if not request.session.has_key('customer_email'):

        return redirect('customer:login')

    customer_email = request.session['customer_email']

    customer = Customer.objects.get(email=customer_email)

    if request.method == "POST":

        product_id = request.POST['product_id']

        product = Product.objects.get(id=product_id)

        shop = Shop.objects.get(id=shop_id)

        total_price = request.POST['total_price']

        count = request.POST['count']

        address = request.POST['address']

        order = Order.objects.create(product=product, shop=shop,

                                     total_price=total_price, count=count, customer=customer, address=address)

        order.save()

        return redirect('customer:my_orders')


def product_page(request, shop_id, product_id):

    try:

        shop = Shop.objects.get(id=shop_id)

    except:

        shop = None

    try:

        product = Product.objects.get(id=product_id)

    except:

        product = None

    try:

customer/templates/customer/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
      crossorigin="anonymous"
    ></script>
    <title>{% block title %}{% endblock%}</title>
    {%block style%}{%endblock%}
    <style>
      {% comment %} making footer at end of page {% endcomment %}
      .div1 {
        min-height:100vh;
        display:flex;
        flex-direction:column;
      }
      main{
        flex-grow:1;
      }
      footer{
        margin-top:auto;
        background-colour:#f1f1f1;
      }
      {% comment %} body{
        background-color:rgb(255,235,194);
      } {% endcomment %}
    </style>
  </head>
  <body>
      <div class="div1">
          <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
              <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'customer:home' %}">Shopify</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-flex justify-content-end mr-5" id="navbarNav">
                  <ul class="navbar-nav">
                    {% if cust %}
                    <li class="nav-item dropdown mr-5">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{cust.name}}
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'customer:profile'%}">My Profile</a></li>
                        <li><a class="dropdown-item" href="#">Favourates</a></li>
                        <li><a class="dropdown-item" href="{% url 'customer:my_orders'%}">My Order</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'customer:logout'%}">Log Out</a></li>
                      </ul>
                    </li>
                    {% else %} 
                    <li class="nav-item">
                      <a class="nav-link" href = "{% url 'customer:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                      <a class = "nav-link" href="{% url 'customer:register' %}">Register</a>
                    </li>
                    {% endif %}
                  </ul>
                </div>
              </div>
          </nav>
          <main>
            {% block content %}{% endblock%}
          </main>
          {% include 'customer/footer.html' %}
      </div>
        {% block page_script %}{% endblock %}
  </body>
</html>

customer/templates/customer/footer.html
<footer>
</br>
<hr>
    <div class="d-flex justify-content-around">
        <h4 ><a class="text-decoration-none" href="{% url 'customer:home'%}">Shopify</a></h4>
        <h4 ><a class="text-decoration-none" href="{% url 'shopowner:home'%}">Join Us</a></h4>       
    </div>
    <div class="text-center">
        <p>&copy;Copyright <span id="Currentyear">2022</span></p>
    </div>
</footer>

<script>
    const d = new Date();
    const thisyear = d.getFullYear();
    document.getElementById('Currentyear').innerHtml = thisyear;  
</script>

customer/templates/customer/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
      crossorigin="anonymous"
    ></script>
    <title>Shopify-Home</title>
    
<style>
    .bkimg{
        position:absolute;
        height:600px;
        width:100%;
        z-index:-1;
        filter:brightness(50%);
        
    }
    .navbar{
         background:transparent;
    }
    .hmblwnav{
        padding-top: 300px;
        padding-left: 10%;
        padding-right:10%;
        text-align:center;
        color:white
    }

    {% comment %} now for making footer at end of page {% endcomment %}
    .container{
      min-height:100vh;
      display:flex;
      flex-direction:column;
    }
    .container .hmblwnav{
      flex-grow:1;
    }
    .container footer{
      background-color:#f1f1f1;
      margin-top:auto;
    }

  </style>
</head>
<body>
 <img class="bkimg" src="{% static 'customer/shopify_home_store.jpg'%}"/>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark  hmnav">
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'customer:home' %}">Shopify</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-flex justify-content-end mr-5" id="navbarNav">
              <ul class="navbar-nav">
                {% if cust %}
                <li class="nav-item dropdown mr-5">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {{cust.name}}
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'customer:profile'%}">My Profile</a></li>
                    <li><a class="dropdown-item" href="#">Favourates</a></li>
                    <li><a class="dropdown-item" href="{% url 'customer:my_orders'%}">My Order</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'customer:logout'%}">Log Out</a></li>
                  </ul>
                </li>
                {% else %} 
                <li class="nav-item">
                  <a class="nav-link" href = "{% url 'customer:login' %}">Login</a>
                </li>
                <li class="nav-item">
                  <a class = "nav-link" href="{% url 'customer:register' %}">Register</a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
      </nav>


        <div class="hmblwnav">
            <h3>Find Shop At Your Place</h3>
            <form class="row" action="{% url 'customer:results' %}" method="get">
                <div class="col mr-0">
                    <input class="form-control" name="city_name" id="city_name" type="text" placeholder="City Name" required/>
                </div>
                <div class="col mr-0">
                    {% comment %} <input class="form-control" name="sshop" id = "sshop" type="text" placeholder = "Search By Shop Name"/> {% endcomment %}
                    <div class="input-group mb-3">
                      <input type="text" class="form-control"  placeholder="Search by..." name = "shop" id = "searchingfield">
                      <select class="form-select dropdown-toggle" id = "select_search">
                        <option value = "shop" selected>Shop</option>
                        <option value="product">Product</option>
                      </select>
                    </div>
                </div>
                <div class="text-center mt-5">
                <button class="btn btn-primary">Search</button>
                </div>
                
            </form>
        </div>

      {% include 'customer/footer.html'%}
      </div>
  </body>
</html>


{% block page_script %}
  <script>
    let searchingfield = document.getElementById("searchingfield");
    let select_search = document.getElementById("select_search");
    select_search.addEventListener('change',()=>{
      if(select_search.value == "shop"){
        searchingfield.name= "shop";
      }
      else{
        searchingfield.name= "product";
      }
    })
  </script>
{% endblock page_script %}

customer/templates/customer/login.html
{% extends 'customer/base.html' %}

{% block title %}
Shopify-Login
{% endblock title %}


{% block content%}
    <div class= "container w-25 shadow p-3 mb-5 bg-body rounded">
            <h1>Login Page</h1>
            <form action="/login" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="email" class="form-label" >Email</label>
                    <input id = "email" name="email" type = "email" class="form-control" required />
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control" id="password" name="password" required/>
                </div>
                {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{error}}
                  </div>
                {% endif %}
                </br>
                <button class="btn btn-sm btn-primary " type="submit">Login</button>
            </form>
        </br>
            <h3 class="text-center">Dont have account? Do <a href="{% url 'customer:register'%}">register</a></h3>
    </div>
{%endblock content%}

customer/templates/customer/product_result.html
{% extends 'customer/base.html' %}

{% block title %}
Shopify
{% endblock title %}

{% block style %}
<style>
    a{
        text-decoration:none;
        color:none;
    }
</style>
{% endblock style %}

{% block content %}
    {% ifequal list_length 0 %}
    <h2>No Products with this name </h2>
    <h3>You can try searching with some different keyword </h3>
    {% else %}
    <h2>Product with name '{{pname}}' present in {{shop.name}} shop are -</h2>
    <div class = "container mt-5 text-center">
        <div class="row">
          <div class = "col-md-10 offset-1">
            {% for product in products %}
            <div class="card mb-5 container" style="width: 18rem;">
                <img class="card-img-top" src="{{ product.image.url }}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{product.name}}</h5>
                    <p class="card-text">product details:  {{product.details}}</p>
                    {% if product.discount == 0.0%}
                    <p class="card-text">Price - {{product.price}}/{{product.unit}}</p>
                    {% else %}
                    <p class="card-text">Price- <del>{{product.price}}/{{product.unit}}</del> {{product.get_discounted_price}}/{{product.unit}}</p>
                    {% endif %}
                </div>
                <a class="btn btn-sm btn-primary" href="{% url 'customer:product_page' shop.id product.id %}">Visit</a>
            </div>
            {% endfor %}
          </div>
        </div>
    </div>
    {% endifequal %}
{% endblock content %}

customer/templates/customer/results.html
{% extends 'customer/base.html' %}

{% block title %}
Shopify
{% endblock title %}

{% block style %}
<style>
    a{
        text-decoration:none;
        color:none;
    }
    .card:hover{
      background-color:#E3F2FD;
    }
</style>
{% endblock style %}

{% block content %}
    {% ifequal list_length 0 %}
    <h2>No shop/Products with this name </h2>
    <h3>You can try searching with some different keyword </h3>
    {% else %}
    {% if shops %}
    <div class="container mt-5 text-center">
            
              <div class="row">
                <div class="col-md-10 offset-1">
                  {% for shop in shops %}
                    <div class="card mb-5" style= "max-width:1000px;height:180px;">
                      <a href = "{% url 'customer:shop_page' shop.id%}" style="text-decoration:none;color:black">
                        <div class="row g-3">
                          <div class="col-md-4">
                            <img src = "{{shop.image.url}}" alt = "Card image cap" style="width:270px;height:180px;">
                          </div>
                          <div class="col-md-8">
                            <div class="card-body">
                              <h5 class="card-title">{{shop.name}}</h5>
                              <p class="card-text">Shop Address:  {{shop.address}}</p>
                            </div>
                          </div>
                        </div>

                      </a>
                    </div>
                  {% endfor %}
                </div>
              </div>
            </div>
    {% elif products %}
    <div class = "container mt-5 text-center">
        <div class="row">
          <div class = "col-md-10 offset-1">
            {% for product in products %}
        {% comment %} <h2>{{product.name}} is available in following shops - </h2> {% endcomment %}
            {% for shop in product.shop.all %}
            <div class="card mb-3" style="max-width: 1000px;height:180px;">
                <a href="{% url 'customer:product_page' shop.id product.id%}" style="text-decoration: none; color:black;">
                  <div class="row g-3">
                    <div class="col-md-4">
                      <img src="{{product.image.url}}" class="img-fluid rounded-start" alt="Card image" style="width:270px;height:180px;">
                    </div>
                    <div class="col-md-8">
                      <div class="card-body">
                        <h5 class="card-title">{{product.name}}</h5>
                        <p class="card-text">{{product.details}}</p>
                        {% if product.discount == 0.0%}
                        <p class="card-text">Price - {{product.price}}/{{product.unit}}</p>
                        {% else %}
                        <p class="card-text">Price- <del>{{product.price}}/{{product.unit}}</del> {{product.get_discounted_price}}/{{product.unit}}</p>
                        {% endif %}
                        <p class="card-text"><small class="text-muted">Shop Name: {{shop.name}}</small></p>
                      </div>
                    </div>
                      </div>
                </a>
                </div>
            {% endfor%}
        <hr/>
        {% endfor %}
          </div>
        </div>
    </div>
    {% endif %}
    {% endifequal %}
{% endblock content %}

customer/templates/customer/shop_profile.html
{% extends 'customer/base.html' %}

{% block title %}
Shopify-{{shop.name}}
{% endblock title %}

{% block style %}
<style>
    .container{
        background:linear-gradient(#FCBBFF,#D6FFFF);
    }
</style>
{% endblock style %}
{% block content %}


    <div class = "container text-center mt-5">
        {% if not_found %}
         <h1>Shop Doesn't Exist, Please Check Again
        {% else %}    
            <img class="img-thumbnail" src="{{shop.image.url}}" height=500px width=500px>
            <h2>{{shop.name}}</h2>
            <h5>Shop-owner: {{shop.shopowner.name}}</h5>
                </br></br></br></br>
            {% comment %} <h3></h3>   here we can add contact number of Shop
            {% endcomment %} 
            {% if product_request_done %} 
            <div class="alert alert-dark alert-dismissible fade show" role="alert">
                <strong>Thank You</strong> for requesting the product. We will make it available soon.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {% endif %}


            <h5>You can search Your Product here</h5>
            <form action = "{% url 'customer:shop_page_result' shop.id %}" method="get">
                <input class="form-control" placeholder="Search Product Name" name="product_name" type="text"/>
                <button class="btn btn-sm btn-outline-primary">Search</button>
            </form>

        </br>
        <hr>
        </br>
        <div>
            <h3>Latest Products Added in Shop</h3>
                <div class=" d-flex flex-wrap">
                    {% for product in products %}
                    <a href="{% url 'customer:product_page' shop.id product.id %}" style = "text-decoration:none; color:black">
                    <div class="card mx-2 my-2" style="width: 18rem;">
                        <img class="card-img-top" src="{{product.image.url}}" alt="Card image cap">
                        <div class="card-body">
                        <h5 class="card-title">{{product.name}}</h5>
                        {% if product.discount == 0.0%}
                        <p class="card-text">Price - {{product.price}}/{{product.unit}}</p>
                        {% else %}
                        <p class="card-text">Price- <del>{{product.price}}/{{product.unit}}</del> {{product.get_discounted_price}}/{{product.unit}}</p>
                        {% endif %}
                        </div>
                    </div>
                </a>
                    {% endfor %}
                </div>
        </div>
        {% endif %}
    </div>
{% endblock content %}