shopify/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("customer.urls", namespace="customer")),
    path('partner_with_us/', include("shopowner.urls", namespace="shopowner")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopowner/urls.py
from django.urls import path
from .views import *

app_name = "shopowner"

urlpatterns = [
    path('', home, name='home'),
    path('login', login, name='login'),
    path('register', register, name='register'),
    path('complete_register', complete_register, name='complete_register'),
    path('profile', profile, name='profile'),
    path('logout', logout, name="logout"),
    path('add_shop', add_shop, name="add_shop"),
    path('order/<int:orderid>/', order, name="order"),
    path('my_shop/<int:shopid>/notification/',
         shop_notification, name="shop_notification"),
    path('my_shop/<int:shopid>/orders/', shop_orders, name="shop_orders"),
    path('my_shop/<int:shopid>/product/<int:productid>/',
         edit_product, name="edit_product"),
    path('my_shop/<int:shopid>/', shop_profile, name="my_shop"),
]

shopowner/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db.models.deletion import CASCADE
from customer.models import Customer
# Create your models here.


class Shopowner(models.Model):

    user = models.OneToOneField(User, on_delete=CASCADE)
    age = models.IntegerField(validators=[MinValueValidator(18)], null=True)
    profile_complete = models.BooleanField(default=False)
    address = models.CharField(max_length=100, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=50, null=True)
    image = models.ImageField(
        upload_to="shopowner/images", default="shopowner/images/shopowner_default.jpg")

    def name(self):
        return self.user.first_name + " " + self.user.last_name

    def __str__(self):
        return self.name()


class Product(models.Model):
    name = models.CharField(max_length=40)
    details = models.CharField(max_length=150)
    price = models.IntegerField()
    image = models.ImageField(
        upload_to="product/images", default="product/images/product_default.jpg")
    # this will be measuring unit
    unit = models.CharField(max_length=50, default="Kg")
    # discount will be in Percentage
    discount = models.FloatField(default="0")

    def __str__(self):
        return self.name + " " + self.details

    @property
    def get_discounted_price(self):
        discount = self.discount
        price = self.price
        discounted_price = price - (discount/100)*price
        return discounted_price


class Shop(models.Model):
    name = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=50, null=True)
    shopowner = models.ForeignKey(
        Shopowner, on_delete=models.CASCADE, default="", related_name='shop')
    products = models.ManyToManyField(Product, related_name='shop')
    image = models.ImageField(upload_to="shop/images",
                              default="shop/images/shop_default.jpg")

    def __str__(self):
        return self.name


class Notification(models.Model):
    message = models.TextField(null=True)
    tag = models.CharField(max_length=50, default="review")
    customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE, default="")
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE, default="")

    def __str__(self):
        return self.message


class Order(models.Model):
    # tells the product of order
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    # tells the shop to which order belongs
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE)  # customer who order this
    total_price = models.IntegerField(
        default=0)    # total price of this product
    # tells if order is completed or not
    completed = models.BooleanField(default=False)
    count = models.IntegerField(default=1)    # number of products in order
    status = models.CharField(
        default="pending", max_length=20)  # status of order
    address = models.CharField(
        null=True, max_length=70)         # address for order

    def __str__(self):
        return f'${self.product.name}-${self.shop.name}'

shopowner/views.py
from django.http.response import HttpResponse

from django.shortcuts import redirect, render

from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User

from django.contrib.auth import login as auth_login, authenticate, logout as auth_logout

from .models import Notification, Product, Shop, Shopowner, Order

# Create your views here.


def home(request):

    if not request.user.is_authenticated or not hasattr(request.user, "shopowner"):

        return redirect('shopowner:login')

    if hasattr(request.user, "shopowner"):

        return render(request, "shopowner/home.html", {
            'user': request.user,

            'shops': request.user.shopowner.shop.all()

        })

    return render(request, 'shopowner/home.html', {
        'user': request.user

    })


def login(request):

    if request.user.is_authenticated and hasattr(request.user, "shopowner"):

        return redirect('shopowner:home')

    if request.method == 'POST':

        email = request.POST['email']

        password = request.POST['password']

        if User.objects.filter(email=email).exists():

            usr = User.objects.get(email=email)

            if hasattr(usr, "shopowner"):

                if password != usr.password:

                    error = "Incorrect Password"

                    return render(request, 'shopowner/login.html', {

                        'user': None,
                        'error': error

                    })

                auth_login(request, usr)

                return redirect('shopowner:home')
            else:

                error = "User with this email does not exist"

                return render(request, "shopowner/login.html", {
                    'error': error,

                    'user': None

                })
        else:

            error = "User with this email does not exist"

            return render(request, 'shopowner/login.html', {
                'error': error,

                'user': None

            })

    return render(request, 'shopowner/login.html', {

        'user': None

    })


def register(request):

    if request.method == "POST":

        username = request.POST['username']

        email = request.POST['email']

        first_name = request.POST['first_name']

        last_name = request.POST['last_name']

        if User.objects.filter(username=username).exists():

            error = "User with username already exists, use some differet username"

            return render(request, 'shopowner/register.html', {

                'user': None,
                'error': error

            })

        if User.objects.filter(email=email).exists():

            error = "User with this email already exists"

            return render(request, 'shopowner/register.html', {

                'user': None,
                'error': error

            })

        password = request.POST['password']

        con_password = request.POST['con_password']

        if password != con_password:

            error = "Password does not match"

            return render(request, 'shopowner/register.html', {
                'error': error,

                'user': None

            })

        u = User(username=username, email=email,

                 password=password, first_name=first_name, last_name=last_name)

        u.save()

        auth_login(request, u)

        owner = Shopowner(user=u)

        owner.save()

        return redirect('shopowner:complete_register')

    return render(request, 'shopowner/register.html', {

        'user': None

    })


def logout(request):

    if request.method == "POST":

        auth_logout(request)

        return redirect('shopowner:home')

    return render(request, 'shopowner/logout.html')


def profile(request):
    pass


def jls_extract_def(request):
    return request


def complete_register(request):
    user = request.user

    if request.method == "POST":

        owner = user.shopowner

        owner.age = request.POST['age']

        owner.address = request.POST['address']

        owner.city = request.POST['city']

        owner.state = request.POST['state']

        try:

            img = request.FILES['image']

        except:

            img = None

        if img:

            owner.image = img

        owner.profile_complete = True

        owner.save()

        return redirect('shopowner:home')
    return render(request, 'shopowner/complete_register.html', {
        'user': user,
    })


@login_required(login_url="/partner_with_us/login")
def add_shop(request):

    if not hasattr(request.user, "shopowner"):

        return redirect('shopowner:login')

    if request.method == "POST":
        user = request.user

        shopowner = Shopowner.objects.get(user=user)

        name = request.POST['name']

        address = request.POST['address']

        city = request.POST['city']

        state = request.POST['state']

        shop = Shop(name=name, address=address, city=city,

                    state=state, shopowner=shopowner)

        # now getting image

        try:

            img = request.FILES['image']

        except:

            img = None

        if img:

            shop.image = img

        shop.save()

        return redirect('shopowner:home')

    return render(request, 'shopowner/add_shop.html', {
        'user': request.user

    })


@login_required(login_url="/partner_with_us/login")
def shop_profile(request, shopid):

    usr = request.user

    shops = usr.shopowner.shop.all()

    try:

        s = shops.get(id=shopid)

    except:

        s = None

    if s and request.method == "POST":  # add products to this shop

        name = request.POST['name']

        details = request.POST['detail']

        price = request.POST['price']

        unit = request.POST['unit']

        discount = request.POST['discount']

        product = Product(name=name, details=details,
                          price=price, unit=unit, discount=discount)

        try:

            image = request.FILES['image']

        except:

            image = None

        if image:

            product.image = image

        product.save()
        s.products.add(product)

        s.save()

        return redirect('shopowner:my_shop', s.id)

    return render(request, "shopowner/shop_profile.html", {
        'user': request.user,

        'shop': s,

        'products': s.products.all()[:5]

    })


@login_required(login_url="partner_with_us/login")
def shop_notification(request, shopid):

    s = Shop.objects.get(id=shopid)

    notification = Notification.objects.filter(shop=s)

    notifications_count = notification.count()

    return render(request, "shopowner/shop_notification.html", {
        'user': request.user,
        'shop': s,

        'notifications': notification,

        'notifications_count': notifications_count,

    })


@login_required(login_url='partner_with_us/login')
def edit_product(request, shopid, productid):

    shop = Shop.objects.filter(id=shopid).first()

    product = Product.objects.filter(id=productid).first()

    if request.method == "POST":

        product.name = request.POST['name']

        product.details = request.POST['details']

        product.price = request.POST['price']

        product.unit = request.POST['unit']

        product.discount = request.POST['discount']

        try:

            product.image = request.FILES['image']

        except:
            pass

        product.save()

        return redirect('shopowner:my_shop', shopid)

    return render(request, 'shopowner/shop_edit_product.html', {
        'product': product,
        'user': request.user,

        'shop': shop})


@login_required(login_url='partner_with_us/login')
def shop_orders(request, shopid):

    shop = Shop.objects.filter(id=shopid).first()

    orders = Order.objects.filter(shop=shop)
    print(shop)

    return render(request, 'shopowner/shop_orders.html', {
        'shop': shop,
        'orders': orders,
        'user': request.user

    })


@login_required(login_url='partner_with_us/')
def order(request, orderid):

    order = Order.objects.filter(id=orderid).first()

    if request.method == "POST" and request.POST.get('change_order_status') == 'submit':

        status = request.POST['order_status']
        order.status = status

        order.save()

    return render(request, 'shopowner/order_page.html', {
        'user': request.user,
        'order': order

    })

shopowner/templates/shopowner/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
      crossorigin="anonymous"
    ></script>
    <title>{%block title%}{% endblock %}</title>
    <style>
        .div-main{
          min-height:100vh;
          display:flex;
          flex-direction:column;
        }
        main{
          flex-grow:1;
        }
        footer{
          margin-top:auto;
          background-color:#f1f1f1;
        }
        img{
          max-height:400px;
          max-width:100%;
          height:auto;
          width:auto;
        }
    </style>
  </head>
  <body>
    <div class="div-main">
      <nav class="navbar navbar-expand-lg navbar-light"  style="background-color: #e3f2fd;">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'shopowner:home'%}"
            >Shopify-Partner</a
          >
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div
            class="collapse navbar-collapse d-flex justify-content-end mr-5"
            id="navbarNav"
          >
            <ul class="navbar-nav">
              {% if user %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'shopowner:add_shop'%}"
                  >Add Shop</a
                >
              </li>
              <li class="nav-item dropdown mr-5">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  {{user.username}}
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">My Profile</a></li>
                  <li><a class="dropdown-item" href="#">My Shops</a></li>
                  <li><hr class="dropdown-divider" /></li>
                  <li>
                    <a class="dropdown-item" href="{% url 'shopowner:logout'%}"
                      >Log Out</a
                    >
                  </li>
                </ul>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'shopowner:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'shopowner:register' %}"
                  >Register</a
                >
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      <main>
        {% block content %}{% endblock content %} 
      </main>
      {%include 'shopowner/footer.html'%}
    </div>
  </body>
</html>

shopowner/templates/shopowner/footer.html
<footer>
</br>
<hr>
    <div class="d-flex justify-content-around">
        <h4 ><a class="text-decoration-none" href="{% url 'shopowner:home'%}">Shopify</a></h4>
        <h4 ><a class="text-decoration-none" href="{% url 'customer:home'%}">Buy Some Product</a></h4>       
    </div>
    <div class="d2">

    </div>
    <div class="text-center">
        <p>&copy;Copyright <span id="Currentyear">2022</span></p>
    </div>
</footer>

<script>
    const d = new Date();
    const thisyear = d.getFullYear();
    document.getElementById('Currentyear').innerHtml = thisyear;  
</script>

shopowner/templates/shopowner/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
      crossorigin="anonymous"
    ></script>
    <title>Shopify-Home</title>
    
<style>
    .bgimg{
        position:absolute;
        height:600px;
        width:100%;
        z-index:-1;
        filter:brightness(50%);
        
    }
    .navbar{
         background:transparent;
    }
    .hmblwnav{
        padding-top: 300px;
        padding-left: 10%;
        padding-right:10%;
        text-align:center;
        color:white
    }
    .div2{
      margin:0 22%;
    }

    {% comment %} making footer at end of page {% endcomment %}
    .div-main{
      min-height:100vh;
      display:flex;
      flex-direction:column;
    }
    .div2{
      flex-grow:1;
    }
    footer{
      margin-top:auto;
      background-color:#f1f1f1;
    }
</style>
</head>
<body>
    <img class="bgimg"  src="{% static 'shop/shop_home_page.jpg' %}"/>
    <div class = "div-main">
      <div class="container div1">
          <nav class="navbar navbar-expand-lg navbar-dark hmnav">
              <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'shopowner:home'%}">Shopify-Partner</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-flex justify-content-end mr-5" id="navbarNav">
                  <ul class="navbar-nav">
                    {% if user %}
                    <li class="nav-item">
                      <a class="nav-link" href = "{% url 'shopowner:add_shop'%}">Add Shop</a>
                    </li>
                    <li class="nav-item dropdown mr-5">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{user.username}}
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">My Profile</a></li>
                        <li><a class="dropdown-item" href="#">My Shops</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'shopowner:logout'%}">Log Out</a></li>
                      </ul>
                    </li>
                    {% else %} 
                    <li class="navk-item">
                      <a class="nav-link" href = "{% url 'shopowner:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                      <a class = "nav-link" href="{% url 'shopowner:register' %}">Register</a>
                    </li>
                    {% endif %}
                  </ul>
                </div>
              </div>
          </nav>
          <div class="text-center">
          <h2 style="margin-top:250px; margin-bottom:250px;color:white;">Welcome {{user.shopowner.name}}</h2>
          </div>
      </div>
      <div class="conatainer text-center div2">
            </br></hl></br>
            <h3>Your Shops list</h3>
            <div class="d-flex flex-wrap">
              {% for shop in shops %}
              <div class="card mx-3 my-3" style="width: 20rem;">
                <img class="card-img-top" src="{{shop.image.url}}" alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title">{{shop.name}}</h5>
                  <p class="card-text">Shop Address: {{shop.address}}</p>
                  <a href="{% url 'shopowner:my_shop' shop.id %}" class="btn btn-primary">Visit Shop</a>
                </div>
              </div>
              {% endfor %}
            </div> 
      </div>
      {% include 'shopowner/footer.html' %}
    </div>
  </body>

shopowner/templates/shopowner/login.html
{% extends 'shopowner/base.html' %}

{% block title %}
Login
{% endblock title %}

{% block content %} 
<div class= "container w-25 shadow p-3 mb-5 bg-body rounded">
  <h1>Login Page</h1>
  <form action="/partner_with_us/login" method="post">
      {% csrf_token %}
      <div class="mb-3">
          <label for="email" class="form-label" >Email</label>
          <input id = "email" name="email" type = "email" class="form-control" required />
      </div>
      <div class="mb-3">
          <label for="password" class="form-label">Password</label>
          <input type="password" class="form-control" id="password" name="password" required/>
      </div>
      {% if error %}
      <div class="alert alert-danger" role="alert">
          {{error}}
        </div>
      {% endif %}
      </br>
      <button class="btn btn-sm btn-primary " type="submit">Login</button>
  </form>
</br>
  <h3 class="text-center">Dont have account? Do <a href="{% url 'shopowner:register'%}">register</a></h3>
</div>
{% endblock content %}

shopowner/templates/shopowner/logout.html
{% extends 'shopowner/base.html' %}

{% block title %}
logout  
{% endblock title %}

{% block content %}
    <div class="container">
        <h1>Do you really want to logout?</h1>
        <form action="/partner_with_us/logout" method = 'post'>
            {% csrf_token %}
            <button class="btn btn-sm btn-danger">Logout</button>
        </form>
    </div>

{% endblock content %}

shopowner/templates/shopowner/order_page.html
{% extends 'shopowner/base.html' %}

{% block content %}

<div class="container text-center">
</br>
    <div class="mt-4">
    <img class="img-thumbnail  shadow p-3 mb-5 bg-body rounded" alt="order image" src="{{order.product.image.url}}" style = "height:500px; width:500px;">
    </div>
    <div class="card shadow p-3 mb-5 bg-body rounded">
        <div class="card-body">
            <h3 class="card-title">{{order.product.name}}</h3>
            <p class = "card-text">Ordered By - {{order.customer.name}}</p>
            <p class = "card-text">Address - {{order.address}}</p>
            <p class = "card-text">Quantity - {{order.count}}</p>
            <p class = "card-text">Price - {{order.total_price}}</p>
            <form class="form" method="Post" action="{% url 'shopowner:order' order.id%}">
                {% csrf_token %}
                <p class="card-text">Current Status - {{order.status}}</p>
                <div class="mb-3 row">
                    <div class="col-sm-4 offset-4">
                        <label class="me-3  " for="order_status" class="form-label">Change Status</label>
                        <div class="d-inline-block">
                        <select class="form-select" aria-label="select" name = "order_status">
                            <option value = "pending">Pending</option>
                            <option value = "cancelled">Cancelled</option>
                            <option value = "completed">Completed</option>
                            <option value = "shipped">Shipped</option>
                            <option value = "on-hold">On-hold</option>
                          </select>
                        </div>
                        <button class="btn btn-outline-primary mb-1" type="submit" value = "submit" name="change_order_status">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    

</div>
{% endblock content %}

shopowner/templates/shopowner/shop_orders.html
{% extends 'shopowner/base.html'%}

{% block content %}
    {% if not shop %}
        <h1>Shop dosen't exits<h1>
    {% else %}
    <h1> Orders of your shop </h1>
  
    <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Product</th>
            <th scope="col">Customer</th>
            <th scope = "col">Quantity</th>
            <th>Total Price</th>
            <th scope="col">Status</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
        {% for order in orders %}
        <tr>
            <td>{{order.product.name}}</td>
            <td>{{order.customer.name}}</td>
            <td>{{order.count}}</td>
            <td>{{order.total_price}}</td>
            <td>Status : {{order.status}}</td>
            <td><a class="btn btn-sm btn-primary" href="{% url 'shopowner:order' order.id%}">View Order</a></td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    {% endif %}
{% endblock content %}

shopowner/templates/shopowner/shop_profile.html
{% extends 'shopowner/base.html' %}
{% load mathfilters %}

{% block title %}
Shopify - {{shop.name}}
{% endblock title %}

{% block content %}
    <div class="container w-50 text-center">
            <h1 class="">{{shop.name}}</h1>
            <h5>{{shop.shopowner.name}}</h5>
            <div class="row">
                <div class="col">
                    <h5><a class="btn btn-primary" href="{% url 'shopowner:shop_notification' shop.id %}">Check Notification</a></h5>
                </div>
                <div class="col">
                    <h5><a class="btn btn-primary" href = "{% url 'shopowner:shop_orders' shop.id%}">Check Orders</a></h5>
                </div>
            </div>
        </br></br><hr></br>
        <h3>Recently Added Products</h3>
        <div class=" d-flex flex-wrap" >
            {% for product in products %}
            <div class="card mx-2 my-2" style="width: 18rem;">
                <img class="card-img-top" src="{{product.image.url}}" alt="Card image cap" style="width:100%;height:300px;">
                <div class="card-body" style="margin-top:auto;">
                <h5 class="card-title">{{product.name}}</h5>
                {% if product.discount == 0.0 %}
                        <p>Price  =  {{product.price}}/{{product.unit}}</p>
                {% else %}
                       <p> Price = <del>{{product.price}}/{{product.unit}}</del> {{product.get_discounted_price}}/{{product.unit}}</p>
                {% endif %}
                <p class="card-text">Discount : {{product.discount}}%</p>
                <a class="btn btn-sm btn-primary" href="{% url 'shopowner:edit_product' shop.id product.id%}">Edit product</a>
                </div>
            </div>
            {% endfor %}
            </div>
        </br></br>
        <hr>
    <section>
    <h4>Add Product to your shop</h4>
        <div class="container wd-50">
            <form action="{% url 'shopowner:my_shop' shop.id%}"  method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="ml-3 my-1">
                    <label for="name" class="form-label">Name</label>
                    <input id = "name" name="name" class="form-control" type="text" required/>
                </div>
                <div class="ml-3 my-1">
                    <label for="image" class="iform-label">Upload image of Product</label>
                    <input id = "image" name="image" class="form-control" type="file" accept = "image/*"/>
                </div>
                <div class="ml-3 my-1">
                    <label for="price" class="form-label">Price</label>
                    <input id = "price" name="price" class="form-control" type="number" required/>
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                      <label class="input-group-text" for="unit">Price of Product is per</label>
                    </div>
                    <select class="custom-select" id="unit" name="unit">
                      <option value="Kg" >Kg (Kilogram)</option>
                      <option value="l">l (liter)</option>
                      <option value="Packet">Packet</option>
                      <option value ="Dozen">Dozen</option>
                      <option value = "Unit">Unit</option>
                    </select>
                  </div>
                <div class="ml-3 my-1">
                    <label for="detail" class="form-label">Product Detail</label>
                    <input id = "detail" name="detail" class="form-control" type="text" required/>
                </div>
                <div class="ml-3 my-1">
                    <label for="discount" class="form-label">Discount You want to give(in Percentage)</label>
                    <input id = "discount" name="discount" class="form-control" type="number" step="0.01" placeholder = "0%" required/>
                </div>
                <button class="btn btn-sm btn-primary">Add Product</button>
            </form>
        </div>
    </section>
    </div>
{% endblock content %}